title: Charles Nguyen # your name (or website title) here
logo: "/images/profile_test.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  IT Support Technican, Day Trader 
  <br><br>
  I am a recent college graduate with a computer science major at Temple University. I currently work at the College of Public Health at their IT department. Over the past year, I have been day trading. I started off self-studying the financial markets and manually placing trades to now developing an algorithm for optimal returns on investment. 
  <br><br>
  <a href="https://www.linkedin.com/in/charles-a-nguyen/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
# google_analytics: UA-000000-0 # your Google Analytics tracking ID here
